load info
hiqdev/hiapi-certum pull request #3
Opened 2018-04-20 17:08 UTC by bladeroot

2018-04-22 06:30 UTC, SilverFire requested changes

2018-04-22 06:30 UTC, SilverFire commented on src/CertumTool.php
> +                $cert = $certR['object']->getCertificateDetails();
Нужна проверка на ошибку при запросе

2018-04-22 06:30 UTC, SilverFire commented on src/CertumTool.php
>          if ($cert == null) {
===

2018-04-23 07:49 UTC, bladeroot commented on src/CertumTool.php
> +                $cert = $certR['object']->getCertificateDetails();
Дима, проверка чуть выше (на 2 строки примерно)

2018-04-23 08:00 UTC, hiqsol requested changes
правь

2018-04-23 08:00 UTC, hiqsol commented on src/CertumTool.php
> +                $ca_code = arr::cjoin($certR['object']->getCaBundle()->X509Cert, "\n");
когда можно заюзать просто `implode` - юзай

2018-04-23 08:00 UTC, hiqsol commented on src/CertumTool.php
> +                $status = $cert->certificateStatus ? : $order->certificateDetails->certificateStatus;
IMHO получение serial, status и ca_code лучше перенести ниже, прямо в return, мне бы так было бы понятнее.

2018-04-23 08:15 UTC, merged